<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Spatie\Permission\PermissionRegistrar;

class CurrentDataSeeder extends Seeder
{
    /**
     * Restore the shop snapshot taken from the application database.
     *
     * Framework tables are omitted: migrations, cache, cache_locks, jobs,
     * job_batches, failed_jobs, sessions, password_reset_tokens, and
     * personal_access_tokens.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        foreach (array_keys($this->rows()) as $table) {
            DB::table($table)->truncate();
        }

        foreach ($this->rows() as $table => $rows) {
            if ($rows === []) {
                continue;
            }

            foreach (array_chunk($rows, 100) as $chunk) {
                DB::table($table)->insert($chunk);
            }
        }

        Schema::enableForeignKeyConstraints();

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    /**
     * @return array<string, list<array<string, mixed>>>
     */
    private function rows(): array
    {
        return [
            'users' => [
                [
                    'id' => 1,
                    'name' => 'Test User',
                    'email' => 'testuser3@example.com',
                    'phone' => null,
                    'hourly_rate' => null,
                    'flat_rate' => 0,
                    'email_verified_at' => null,
                    'password' => '$2y$12$gLIbxy6zyjBqKpN9NIWVd.BOle42em2kDSzi2dQmZqJQakN2aCijW',
                    'remember_token' => null,
                    'created_at' => '2026-09-25 06:53:24',
                    'updated_at' => '2026-10-06 04:56:24',
                ],
                [
                    'id' => 2,
                    'name' => 'Lisa DeBona',
                    'email' => 'lisaqdebona@gmail.com',
                    'phone' => '2083183596',
                    'hourly_rate' => null,
                    'flat_rate' => 0,
                    'email_verified_at' => null,
                    'password' => '$2y$12$Nk8BnQIS8WTzgCUqxWzKHuQocyyHjC0D2riKvs80fXUsAFf60NyT2',
                    'remember_token' => null,
                    'created_at' => '2026-09-26 03:22:19',
                    'updated_at' => '2026-10-05 03:30:57',
                ],
                [
                    'id' => 3,
                    'name' => 'Steve Morgan',
                    'email' => 'steve.morgan@autocare.com',
                    'phone' => null,
                    'hourly_rate' => '50.00',
                    'flat_rate' => 1,
                    'email_verified_at' => null,
                    'password' => '$2y$12$FsVmEpSyJ2eN7PMav2eqk.DRztfTG3CJ/vndmM5B3v8O7fO3/yiK2',
                    'remember_token' => null,
                    'created_at' => '2026-09-26 03:23:15',
                    'updated_at' => '2026-10-06 03:00:17',
                ],
                [
                    'id' => 4,
                    'name' => 'Hermie',
                    'email' => 'hermiebarit@gmail.com',
                    'phone' => null,
                    'hourly_rate' => null,
                    'flat_rate' => 0,
                    'email_verified_at' => null,
                    'password' => '$2y$12$nyy2V.MaqHBfQGoMUI0we.yGUYs2nxWlcLqNOip37yvAtSrQJttlW',
                    'remember_token' => null,
                    'created_at' => '2026-09-26 05:59:39',
                    'updated_at' => '2026-09-26 05:59:39',
                ],
                [
                    'id' => 13,
                    'name' => 'Brandon Andersen',
                    'email' => 'b.andersen@autocare.com',
                    'phone' => null,
                    'hourly_rate' => '50.00',
                    'flat_rate' => 1,
                    'email_verified_at' => null,
                    'password' => '$2y$12$lkG/ocBN4twMQ4nH/4S9v.3xmgPauhJgvZIUWXbGAxFFReNSrFTt2',
                    'remember_token' => null,
                    'created_at' => '2026-10-06 03:00:03',
                    'updated_at' => '2026-10-06 03:00:03',
                ],
            ],
            'permissions' => [
                [
                    'id' => 1,
                    'name' => 'users.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 2,
                    'name' => 'users.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 3,
                    'name' => 'users.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 4,
                    'name' => 'users.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 5,
                    'name' => 'roles.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 6,
                    'name' => 'roles.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 7,
                    'name' => 'roles.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 8,
                    'name' => 'roles.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 9,
                    'name' => 'permissions.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 10,
                    'name' => 'permissions.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 11,
                    'name' => 'permissions.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 12,
                    'name' => 'permissions.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 13,
                    'name' => 'products.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 14,
                    'name' => 'products.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 15,
                    'name' => 'products.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 16,
                    'name' => 'products.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 17,
                    'name' => 'brands.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 18,
                    'name' => 'brands.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 19,
                    'name' => 'brands.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 20,
                    'name' => 'brands.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 21,
                    'name' => 'categories.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 22,
                    'name' => 'categories.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 23,
                    'name' => 'categories.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 24,
                    'name' => 'categories.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 25,
                    'name' => 'general-settings.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 26,
                    'name' => 'general-settings.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 27,
                    'name' => 'fees-and-rates.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 28,
                    'name' => 'fees-and-rates.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 29,
                    'name' => 'customers.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 04:33:16',
                    'updated_at' => '2026-09-26 04:33:16',
                ],
                [
                    'id' => 30,
                    'name' => 'customers.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 04:33:16',
                    'updated_at' => '2026-09-26 04:33:16',
                ],
                [
                    'id' => 31,
                    'name' => 'customers.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 04:33:16',
                    'updated_at' => '2026-09-26 04:33:16',
                ],
                [
                    'id' => 32,
                    'name' => 'customers.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 04:33:16',
                    'updated_at' => '2026-09-26 04:33:16',
                ],
                [
                    'id' => 33,
                    'name' => 'vehicles.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 05:10:14',
                    'updated_at' => '2026-09-26 05:10:14',
                ],
                [
                    'id' => 34,
                    'name' => 'vehicles.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 05:10:14',
                    'updated_at' => '2026-09-26 05:10:14',
                ],
                [
                    'id' => 35,
                    'name' => 'vehicles.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 05:10:14',
                    'updated_at' => '2026-09-26 05:10:14',
                ],
                [
                    'id' => 36,
                    'name' => 'vehicles.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 05:10:14',
                    'updated_at' => '2026-09-26 05:10:14',
                ],
                [
                    'id' => 37,
                    'name' => 'estimates.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 06:13:48',
                    'updated_at' => '2026-09-26 06:13:48',
                ],
                [
                    'id' => 38,
                    'name' => 'estimates.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 06:13:48',
                    'updated_at' => '2026-09-26 06:13:48',
                ],
                [
                    'id' => 39,
                    'name' => 'estimates.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 06:13:48',
                    'updated_at' => '2026-09-26 06:13:48',
                ],
                [
                    'id' => 40,
                    'name' => 'estimates.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 06:13:48',
                    'updated_at' => '2026-09-26 06:13:48',
                ],
                [
                    'id' => 41,
                    'name' => 'canned-jobs.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-05 05:24:49',
                    'updated_at' => '2026-10-05 05:24:49',
                ],
                [
                    'id' => 42,
                    'name' => 'canned-jobs.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-05 05:24:49',
                    'updated_at' => '2026-10-05 05:24:49',
                ],
                [
                    'id' => 43,
                    'name' => 'canned-jobs.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-05 05:24:49',
                    'updated_at' => '2026-10-05 05:24:49',
                ],
                [
                    'id' => 44,
                    'name' => 'canned-jobs.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-05 05:24:49',
                    'updated_at' => '2026-10-05 05:24:49',
                ],
                [
                    'id' => 45,
                    'name' => 'workflows.view',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-06 04:39:33',
                    'updated_at' => '2026-10-06 04:39:33',
                ],
                [
                    'id' => 46,
                    'name' => 'workflows.create',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-06 04:39:33',
                    'updated_at' => '2026-10-06 04:39:33',
                ],
                [
                    'id' => 47,
                    'name' => 'workflows.edit',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-06 04:39:33',
                    'updated_at' => '2026-10-06 04:39:33',
                ],
                [
                    'id' => 48,
                    'name' => 'workflows.delete',
                    'guard_name' => 'web',
                    'created_at' => '2026-10-06 04:39:33',
                    'updated_at' => '2026-10-06 04:39:33',
                ],
            ],
            'roles' => [
                [
                    'id' => 1,
                    'name' => 'admin',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 2,
                    'name' => 'super-admin',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:15:57',
                    'updated_at' => '2026-09-26 03:15:57',
                ],
                [
                    'id' => 3,
                    'name' => 'technician',
                    'guard_name' => 'web',
                    'created_at' => '2026-09-26 03:22:37',
                    'updated_at' => '2026-09-26 03:22:37',
                ],
            ],
            'role_has_permissions' => [
                [
                    'permission_id' => 1,
                    'role_id' => 1,
                ],
                [
                    'permission_id' => 2,
                    'role_id' => 1,
                ],
                [
                    'permission_id' => 3,
                    'role_id' => 1,
                ],
                [
                    'permission_id' => 4,
                    'role_id' => 1,
                ],
                [
                    'permission_id' => 1,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 2,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 3,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 4,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 5,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 6,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 7,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 8,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 9,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 10,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 11,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 12,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 13,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 14,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 15,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 16,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 17,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 18,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 19,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 20,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 21,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 22,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 23,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 24,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 25,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 26,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 27,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 28,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 29,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 30,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 31,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 32,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 33,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 34,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 35,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 36,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 37,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 38,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 39,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 40,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 41,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 42,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 43,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 44,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 45,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 46,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 47,
                    'role_id' => 2,
                ],
                [
                    'permission_id' => 48,
                    'role_id' => 2,
                ],
            ],
            'model_has_roles' => [
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 1,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 2,
                ],
                [
                    'role_id' => 3,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 3,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 4,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 5,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 9,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 10,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 11,
                ],
                [
                    'role_id' => 2,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 12,
                ],
                [
                    'role_id' => 3,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => 13,
                ],
            ],
            'model_has_permissions' => [],
            'brands' => [
                [
                    'id' => 1,
                    'name' => 'Bosch Auto',
                    'created_at' => '2026-09-26 03:32:26',
                    'updated_at' => '2026-09-26 03:32:49',
                ],
                [
                    'id' => 2,
                    'name' => 'Bosch',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 3,
                    'name' => 'Fram',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 4,
                    'name' => 'Mobil',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 5,
                    'name' => 'Wix',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 6,
                    'name' => 'NGK',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 7,
                    'name' => 'Interstate',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 8,
                    'name' => 'Gates',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 9,
                    'name' => 'Prestone',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
            ],
            'categories' => [
                [
                    'id' => 1,
                    'name' => 'Uncategorized',
                    'created_at' => '2026-09-26 03:31:39',
                    'updated_at' => '2026-09-26 03:31:39',
                ],
                [
                    'id' => 2,
                    'name' => 'Brakes',
                    'created_at' => '2026-09-26 03:33:06',
                    'updated_at' => '2026-09-26 03:33:06',
                ],
                [
                    'id' => 3,
                    'name' => 'Filters',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 4,
                    'name' => 'Fluids',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 5,
                    'name' => 'Ignition',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 6,
                    'name' => 'Wipers',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 7,
                    'name' => 'Electrical',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 8,
                    'name' => 'Belts',
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
            ],
            'customers' => [
                [
                    'id' => 1,
                    'first_name' => 'Margaret',
                    'last_name' => 'Garcia',
                    'home_address' => '1094 Alpha Avenue',
                    'home_city' => 'Jacksonville Beach',
                    'home_state' => 'FL',
                    'home_zip_code' => '32250',
                    'home_country' => 'United States',
                    'office_address' => null,
                    'office_city' => null,
                    'office_state' => null,
                    'office_zip_code' => null,
                    'office_country' => 'United States',
                    'phone' => '9042425787',
                    'phone_2' => null,
                    'email' => 'mgarcia@dayrep.com',
                    'notes' => 'Lorem ipsum dolor sit amet consectetur adipiscing elit mauris rhoncus, in odio morbi congue laoreet aenean magna ultricies.',
                    'created_at' => '2026-09-26 04:57:08',
                    'updated_at' => '2026-09-26 05:46:39',
                ],
                [
                    'id' => 2,
                    'first_name' => 'Spencer',
                    'last_name' => 'Hudson',
                    'home_address' => '2997 Arbutus Drive',
                    'home_city' => 'Miami Springs',
                    'home_state' => 'FL',
                    'home_zip_code' => '33166',
                    'home_country' => 'United States',
                    'office_address' => null,
                    'office_city' => null,
                    'office_state' => null,
                    'office_zip_code' => null,
                    'office_country' => 'United States',
                    'phone' => '(772) 249-3375',
                    'phone_2' => null,
                    'email' => 'spence7789@gmail.com',
                    'notes' => null,
                    'created_at' => '2026-09-26 06:20:54',
                    'updated_at' => '2026-09-26 06:33:53',
                ],
            ],
            'vehicles' => [
                [
                    'id' => 1,
                    'customer_id' => 1,
                    'year' => 2011,
                    'make' => 'Toyota',
                    'model' => '4Runner',
                    'sub_model' => 'Limited',
                    'transmission' => 'Other',
                    'engine_size' => '4.0L V6 (1GR-FE) Gas',
                    'drivetrain' => '4WD',
                    'type' => 'SUV',
                    'mileage' => 96352,
                    'vin' => 'WDYPE8CC3E5868528',
                    'image_path' => 'vehicles/ceb4HObSFODqILCOSl4h4skHfwd21OZ31pPEKkQW.jpg',
                    'created_at' => '2026-09-26 05:13:46',
                    'updated_at' => '2026-09-26 05:43:51',
                ],
                [
                    'id' => 2,
                    'customer_id' => 1,
                    'year' => 2025,
                    'make' => 'Honda',
                    'model' => 'Pilot',
                    'sub_model' => 'TrailSport',
                    'transmission' => 'Other',
                    'engine_size' => '3.5L DOHC V6 (285 hp, 262 lb-ft torque)',
                    'drivetrain' => 'AWD',
                    'type' => 'SUV',
                    'mileage' => 75861,
                    'vin' => 'JHMES16895S401057',
                    'image_path' => 'vehicles/3voZuOgRGr6r2newviO4rUbCL1AJAX6fY2II9zqz.jpg',
                    'created_at' => '2026-09-26 05:17:35',
                    'updated_at' => '2026-09-26 05:43:26',
                ],
                [
                    'id' => 3,
                    'customer_id' => null,
                    'year' => 2025,
                    'make' => 'Subaru',
                    'model' => 'Legacy',
                    'sub_model' => null,
                    'transmission' => 'CVT',
                    'engine_size' => '2.5L 4-Cylinder BOXER (182 hp)',
                    'drivetrain' => 'AWD',
                    'type' => 'Sedan',
                    'mileage' => null,
                    'vin' => null,
                    'image_path' => 'vehicles/DMHrPnSE6U93FW2StstzOlWy6tn4kLMeXCCmFUM5.jpg',
                    'created_at' => '2026-09-26 05:22:41',
                    'updated_at' => '2026-09-26 05:22:41',
                ],
                [
                    'id' => 4,
                    'customer_id' => 2,
                    'year' => 2021,
                    'make' => 'Toyota',
                    'model' => 'RAV4',
                    'sub_model' => 'XLE Premium',
                    'transmission' => 'Automatic',
                    'engine_size' => '2.5L 4-Cylinder',
                    'drivetrain' => 'AWD',
                    'type' => 'SUV',
                    'mileage' => 38450,
                    'vin' => '2T3C1RFV5MW123456',
                    'image_path' => null,
                    'created_at' => '2026-10-06 03:53:26',
                    'updated_at' => '2026-10-06 03:53:26',
                ],
            ],
            'products' => [
                [
                    'id' => 1,
                    'name' => 'Ceramic brake pad',
                    'description' => null,
                    'unit_price' => '10.00',
                    'margin' => '30.00',
                    'retail_price' => '13.00',
                    'stock_quantity' => 4,
                    'brand_id' => 1,
                    'category_id' => 2,
                    'upc_code' => null,
                    'part_number' => null,
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 03:33:26',
                    'updated_at' => '2026-09-26 06:30:34',
                ],
                [
                    'id' => 2,
                    'name' => 'Ceramic Brake Pad Set',
                    'description' => 'Front ceramic brake pads for common passenger cars. Low dust and quiet stopping.',
                    'unit_price' => '28.50',
                    'margin' => '45.00',
                    'retail_price' => '41.33',
                    'stock_quantity' => 24,
                    'brand_id' => 2,
                    'category_id' => 2,
                    'upc_code' => '028851234001',
                    'part_number' => 'BP-1042',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 3,
                    'name' => 'OE-Quality Oil Filter',
                    'description' => 'Spin-on engine oil filter. Fits many domestic and import applications.',
                    'unit_price' => '6.25',
                    'margin' => '50.00',
                    'retail_price' => '9.38',
                    'stock_quantity' => 40,
                    'brand_id' => 3,
                    'category_id' => 3,
                    'upc_code' => '041652338701',
                    'part_number' => 'OF-3387A',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-10-05 04:12:59',
                ],
                [
                    'id' => 4,
                    'name' => '5W-30 Synthetic Motor Oil, 5 qt',
                    'description' => 'Full synthetic 5W-30 motor oil jug for oil changes.',
                    'unit_price' => '24.00',
                    'margin' => '35.00',
                    'retail_price' => '32.40',
                    'stock_quantity' => 30,
                    'brand_id' => 4,
                    'category_id' => 4,
                    'upc_code' => '071924453001',
                    'part_number' => 'MO-5W30-5',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 5,
                    'name' => 'Engine Air Filter',
                    'description' => 'Panel engine air filter that keeps dirt out of the intake.',
                    'unit_price' => '11.40',
                    'margin' => '55.00',
                    'retail_price' => '17.67',
                    'stock_quantity' => 18,
                    'brand_id' => 5,
                    'category_id' => 3,
                    'upc_code' => '765809491562',
                    'part_number' => 'AF-49156',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 6,
                    'name' => 'Iridium Spark Plug',
                    'description' => 'Long-life iridium spark plug. Sold individually.',
                    'unit_price' => '8.75',
                    'margin' => '60.00',
                    'retail_price' => '14.00',
                    'stock_quantity' => 48,
                    'brand_id' => 6,
                    'category_id' => 5,
                    'upc_code' => '087295546511',
                    'part_number' => 'SP-LFR5AIX',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 7,
                    'name' => 'Beam Wiper Blade, 22 in',
                    'description' => '22-inch beam wiper blade for rain and road spray.',
                    'unit_price' => '9.50',
                    'margin' => '70.00',
                    'retail_price' => '16.15',
                    'stock_quantity' => 16,
                    'brand_id' => 2,
                    'category_id' => 6,
                    'upc_code' => '028851339221',
                    'part_number' => 'WB-22A',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 8,
                    'name' => 'Group 35 Car Battery',
                    'description' => 'Group 35 automotive battery, 650 CCA, for many sedans and crossovers.',
                    'unit_price' => '89.00',
                    'margin' => '40.00',
                    'retail_price' => '124.60',
                    'stock_quantity' => 6,
                    'brand_id' => 7,
                    'category_id' => 7,
                    'upc_code' => '041333356501',
                    'part_number' => 'BAT-35-650',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 9,
                    'name' => 'Serpentine Belt',
                    'description' => 'Multi-rib serpentine belt for the alternator, power steering, and A/C.',
                    'unit_price' => '18.20',
                    'margin' => '50.00',
                    'retail_price' => '27.30',
                    'stock_quantity' => 12,
                    'brand_id' => 8,
                    'category_id' => 8,
                    'upc_code' => '072053608251',
                    'part_number' => 'SB-K060825',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 10,
                    'name' => 'Cabin Air Filter',
                    'description' => 'Cabin filter that reduces dust and pollen in the passenger compartment.',
                    'unit_price' => '12.80',
                    'margin' => '55.00',
                    'retail_price' => '19.84',
                    'stock_quantity' => 20,
                    'brand_id' => 5,
                    'category_id' => 3,
                    'upc_code' => '765809293901',
                    'part_number' => 'CF-2939',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 11,
                    'name' => 'Prediluted Coolant, 1 gal',
                    'description' => '50/50 prediluted antifreeze and coolant, ready to pour.',
                    'unit_price' => '14.60',
                    'margin' => '45.00',
                    'retail_price' => '21.17',
                    'stock_quantity' => 22,
                    'brand_id' => 9,
                    'category_id' => 4,
                    'upc_code' => '079340002100',
                    'part_number' => 'CL-AF2100',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-09-26 04:09:46',
                    'updated_at' => '2026-09-26 04:09:46',
                ],
                [
                    'id' => 12,
                    'name' => 'Crush Washer / Drain Plug Seal',
                    'description' => null,
                    'unit_price' => '1.50',
                    'margin' => '10.00',
                    'retail_price' => '1.65',
                    'stock_quantity' => 500,
                    'brand_id' => null,
                    'category_id' => 1,
                    'upc_code' => null,
                    'part_number' => '10999401',
                    'is_taxable' => 1,
                    'image_path' => null,
                    'created_at' => '2026-10-05 03:59:05',
                    'updated_at' => '2026-10-05 03:59:05',
                ],
            ],
            'product_images' => [
                [
                    'id' => 1,
                    'product_id' => 1,
                    'path' => 'products/nnjlAer2wxaaTCdseOeW1UG6yZuzh3gfGqxd7hXj.jpg',
                    'is_main' => 1,
                    'sort_order' => 0,
                    'created_at' => '2026-09-26 03:38:44',
                    'updated_at' => '2026-09-26 06:30:34',
                ],
                [
                    'id' => 2,
                    'product_id' => 1,
                    'path' => 'products/67bXFavRtUG9k8YR1J8F1euaJeNJ3UvWwdDFUyO3.jpg',
                    'is_main' => 0,
                    'sort_order' => 1,
                    'created_at' => '2026-09-26 03:39:47',
                    'updated_at' => '2026-09-26 06:30:34',
                ],
                [
                    'id' => 3,
                    'product_id' => 1,
                    'path' => 'products/QhHJzMBwGjGUCxy2zLBOPs3vZq4apw06vwHcEl3L.jpg',
                    'is_main' => 0,
                    'sort_order' => 2,
                    'created_at' => '2026-09-26 03:39:47',
                    'updated_at' => '2026-09-26 06:30:34',
                ],
            ],
            'general_settings' => [
                [
                    'id' => 1,
                    'company_name' => 'Auto Care Center, Inc.',
                    'website' => 'https://www.autocarecenterinc.com/',
                    'logo_path' => 'logos/P28UK551n6VHv3YE7NrS3lZX7NkQ4pYCUsCoLYIE.png',
                    'email' => 'info@specialtyvancity.com',
                    'phone' => '(772) 461-2114',
                    'timezone' => 'America/New_York',
                    'address' => '3151 N US Highway 1',
                    'city' => 'Fort Pierce',
                    'state' => 'FL',
                    'zip_code' => '34953',
                    'country' => 'United States',
                    'created_at' => '2026-09-26 03:39:42',
                    'updated_at' => '2026-09-26 03:47:54',
                ],
            ],
            'fee_settings' => [
                [
                    'id' => 1,
                    'shop_supplies_cap' => 'none',
                    'shop_supplies_cap_amount' => null,
                    'shop_supplies_fee' => '7.000',
                    'shop_supplies_fee_type' => 'percent',
                    'shop_supplies_on_parts' => 1,
                    'shop_supplies_on_labor' => 1,
                    'epa_rate' => '7.000',
                    'epa_on_parts' => 1,
                    'epa_on_labor' => 1,
                    'tax_rate' => '7.000',
                    'tax_on_parts' => 1,
                    'tax_on_labor' => 1,
                    'tax_on_epa' => 1,
                    'tax_on_shop_supplies' => 1,
                    'tax_on_subcontract' => 1,
                    'created_at' => '2026-09-26 03:40:03',
                    'updated_at' => '2026-09-26 03:48:43',
                ],
            ],
            'canned_jobs' => [
                [
                    'id' => 1,
                    'name' => 'Oil Change',
                    'created_at' => '2026-10-05 05:26:52',
                    'updated_at' => '2026-10-05 05:26:52',
                ],
            ],
            'canned_job_line_items' => [
                [
                    'id' => 1,
                    'canned_job_id' => 1,
                    'type' => 'part',
                    'description' => 'OE-Quality Oil Filter',
                    'price' => '9.38',
                    'quantity' => '1.00',
                    'discount' => null,
                    'remarks' => null,
                    'sort_order' => 0,
                    'created_at' => '2026-10-05 05:26:52',
                    'updated_at' => '2026-10-05 05:26:52',
                ],
                [
                    'id' => 2,
                    'canned_job_id' => 1,
                    'type' => 'part',
                    'description' => 'Crush Washer / Drain Plug Seal',
                    'price' => '1.65',
                    'quantity' => '1.00',
                    'discount' => null,
                    'remarks' => null,
                    'sort_order' => 1,
                    'created_at' => '2026-10-05 05:26:52',
                    'updated_at' => '2026-10-05 05:26:52',
                ],
            ],
            'custom_workflows' => [
                [
                    'id' => 2,
                    'name' => 'Sprinter Van',
                    'value' => 'custom-7ac68784-b469-4e2a-832a-8258d36dcb5e',
                    'created_at' => '2026-10-06 04:42:42',
                    'updated_at' => '2026-10-06 04:42:42',
                ],
            ],
            'estimates' => [
                [
                    'id' => 1,
                    'number' => 1000,
                    'invoice_sequence' => 1,
                    'invoice_number' => '1001',
                    'order_sequence' => null,
                    'order_number' => null,
                    'customer_id' => 1,
                    'vehicle_id' => 2,
                    'service_writer_id' => 2,
                    'due_date' => '2026-10-05',
                    'customer_comments' => null,
                    'recommendations' => null,
                    'po_number' => 'PO11000',
                    'completed_at' => null,
                    'payment_terms' => 'On Receipt',
                    'order_status' => 'invoice',
                    'workflow' => 'invoices',
                    'authorized_at' => '2026-10-06 04:07:10',
                    'labels' => null,
                    'created_at' => '2026-10-05 04:29:22',
                    'updated_at' => '2026-10-06 04:07:10',
                ],
                [
                    'id' => 4,
                    'number' => 1001,
                    'invoice_sequence' => null,
                    'invoice_number' => null,
                    'order_sequence' => 1,
                    'order_number' => '4001',
                    'customer_id' => 2,
                    'vehicle_id' => 4,
                    'service_writer_id' => 2,
                    'due_date' => '2026-10-06',
                    'customer_comments' => null,
                    'recommendations' => null,
                    'po_number' => 'PO41001',
                    'completed_at' => '2026-10-06 00:00:00',
                    'payment_terms' => 'On Receipt',
                    'order_status' => 'estimate',
                    'workflow' => 'in_progress',
                    'authorized_at' => '2026-10-06 04:31:31',
                    'labels' => null,
                    'created_at' => '2026-10-06 03:56:11',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
                [
                    'id' => 6,
                    'number' => 1002,
                    'invoice_sequence' => null,
                    'invoice_number' => null,
                    'order_sequence' => null,
                    'order_number' => null,
                    'customer_id' => 1,
                    'vehicle_id' => 1,
                    'service_writer_id' => 2,
                    'due_date' => '2026-10-06',
                    'customer_comments' => null,
                    'recommendations' => null,
                    'po_number' => 'PO61002',
                    'completed_at' => '2026-10-06 00:00:00',
                    'payment_terms' => 'On Receipt',
                    'order_status' => 'estimate',
                    'workflow' => 'estimates',
                    'authorized_at' => '2026-10-06 04:30:01',
                    'labels' => null,
                    'created_at' => '2026-10-06 04:29:25',
                    'updated_at' => '2026-10-06 04:30:01',
                ],
            ],
            'estimate_services' => [
                [
                    'id' => 13,
                    'estimate_id' => 1,
                    'name' => 'Oil Change',
                    'notes' => null,
                    'authorized' => 1,
                    'discount_percent' => '0.000',
                    'epa_percent' => '7.000',
                    'shop_supplies_percent' => '7.000',
                    'tax_percent' => '7.000',
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:07:15',
                    'updated_at' => '2026-10-06 04:07:15',
                ],
                [
                    'id' => 17,
                    'estimate_id' => 6,
                    'name' => 'Oil Change',
                    'notes' => null,
                    'authorized' => 0,
                    'discount_percent' => '0.000',
                    'epa_percent' => '7.000',
                    'shop_supplies_percent' => '7.000',
                    'tax_percent' => '7.000',
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:30:01',
                    'updated_at' => '2026-10-06 04:30:01',
                ],
                [
                    'id' => 18,
                    'estimate_id' => 4,
                    'name' => 'Oil Change',
                    'notes' => null,
                    'authorized' => 1,
                    'discount_percent' => '0.000',
                    'epa_percent' => '7.000',
                    'shop_supplies_percent' => '7.000',
                    'tax_percent' => '7.000',
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:31:31',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
            ],
            'estimate_line_items' => [
                [
                    'id' => 29,
                    'estimate_service_id' => 13,
                    'type' => 'part',
                    'description' => 'OE-Quality Oil Filter',
                    'price' => '9.38',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => '["Pending"]',
                    'technician_id' => null,
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:07:15',
                    'updated_at' => '2026-10-06 04:07:15',
                ],
                [
                    'id' => 30,
                    'estimate_service_id' => 13,
                    'type' => 'part',
                    'description' => 'Crush Washer / Drain Plug Seal',
                    'price' => '1.65',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => '["In Progress"]',
                    'technician_id' => null,
                    'sort_order' => 1,
                    'created_at' => '2026-10-06 04:07:15',
                    'updated_at' => '2026-10-06 04:07:15',
                ],
                [
                    'id' => 38,
                    'estimate_service_id' => 17,
                    'type' => 'part',
                    'description' => 'OE-Quality Oil Filter',
                    'price' => '9.38',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => null,
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:30:01',
                    'updated_at' => '2026-10-06 04:30:01',
                ],
                [
                    'id' => 39,
                    'estimate_service_id' => 17,
                    'type' => 'part',
                    'description' => 'Crush Washer / Drain Plug Seal',
                    'price' => '1.65',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => null,
                    'sort_order' => 1,
                    'created_at' => '2026-10-06 04:30:01',
                    'updated_at' => '2026-10-06 04:30:01',
                ],
                [
                    'id' => 40,
                    'estimate_service_id' => 17,
                    'type' => 'labor',
                    'description' => 'Service Fee',
                    'price' => '50.00',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => 3,
                    'sort_order' => 2,
                    'created_at' => '2026-10-06 04:30:01',
                    'updated_at' => '2026-10-06 04:30:01',
                ],
                [
                    'id' => 41,
                    'estimate_service_id' => 18,
                    'type' => 'part',
                    'description' => 'OE-Quality Oil Filter',
                    'price' => '9.38',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => null,
                    'sort_order' => 0,
                    'created_at' => '2026-10-06 04:31:31',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
                [
                    'id' => 42,
                    'estimate_service_id' => 18,
                    'type' => 'part',
                    'description' => 'Crush Washer / Drain Plug Seal',
                    'price' => '1.65',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => null,
                    'sort_order' => 1,
                    'created_at' => '2026-10-06 04:31:31',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
                [
                    'id' => 43,
                    'estimate_service_id' => 18,
                    'type' => 'labor',
                    'description' => 'Service Fee',
                    'price' => '50.00',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => '["In Progress"]',
                    'technician_id' => 13,
                    'sort_order' => 2,
                    'created_at' => '2026-10-06 04:31:31',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
                [
                    'id' => 44,
                    'estimate_service_id' => 18,
                    'type' => 'fee',
                    'description' => 'Shop supplies',
                    'price' => '20.00',
                    'quantity' => '1.00',
                    'discount' => null,
                    'status' => null,
                    'remarks' => null,
                    'technician_id' => null,
                    'sort_order' => 3,
                    'created_at' => '2026-10-06 04:31:31',
                    'updated_at' => '2026-10-06 04:31:31',
                ],
            ],
        ];
    }
}
